### ISSUE TITLE
latest uboot source & bord:orangepi_win & its defconfig.    ethernet issues.

### ISSUE THREAD

**Issue by dksslq** [RobertCNelson/u-boot#12]
ethernet@1c30000 Waiting for PHY auto negotiation to complete......... TIMEOUT !
help

dm tree of eth:

 Class    index  Probed  Driver                Name
 eth         0  [ + ]   eth_sun8i_emac            |-- ethernet@1c30000

**Comment by RobertCNelson** [comment]
@dksslq not sure why you opened this bug here.

Feel free to ask questions here: https://lists.denx.de/listinfo/u-boot

I don't personally have an orangepi to assist you...

Regards,
