### ISSUE TITLE
2015.1 branch causes 'Mach-ID' error for Cubieboard2 and Cubietruck mainline 3.19.2 kernel

### ISSUE THREAD

**Issue by db260179** [RobertCNelson/u-boot#2]
After building v2015.1 I get

Error: unrecognized/unsupported machine ID (r1 = 0x100010bb)

Using v2014.10 works with no issues with the linux mainline kernel

It looks like it is not parsing the correct mach-id to the kernel?

**Comment by RobertCNelson** [comment]
Please contact the developers here:
http://lists.denx.de/mailman/listinfo/u-boot
