### ISSUE TITLE
CAN0

### ISSUE THREAD

**Issue by hjmagadum2002** [RobertCNelson/u-boot#8]
In latest beaglebone Debian released on  17.06.2018  , I  am not able to enable CAN0 . Please guide  to enable CAN0. default i2c2 showing in /dev.

In on eof your blog read as to easily map i2c2 -> dcan0 once booted up into userspace.
Let mw know procedure to enable CAN0
Regards,

Hemant

**Comment by RobertCNelson** [comment]
@hjmagadum2002 

```bash
config-pin P9_19 can
config-pin P9_20 can
```

If that doesn't work, run:

```bash
sudo /opt/scripts/tools/version.sh
```

Regards,

**Comment by hjmagadum2002** [comment]
Hi,

Tried both 
config-pin P9_19 can
config-pin P9_20 can
and 
sudo /opt/scripts/tools/version.sh
Both not working.

beaglebone  loaded  with BBB-blank-debian-9.5-lxqt-armhf-2018-07-15-4gb.img.xz

Regards
Hemant
![cantest1](https://user-images.githubusercontent.com/38034179/43441700-552e2358-94b9-11e8-983c-e677462403e1.png)
![cantest2](https://user-images.githubusercontent.com/38034179/43441701-556308a2-94b9-11e8-8ab5-d07d67c3fbd9.png)
![can_dev](https://user-images.githubusercontent.com/38034179/43442714-643049be-94bc-11e8-8523-165092ed0e16.png)

**Comment by RobertCNelson** [comment]
@hjmagadum2002 ah i see the issue, yeah with the direction your going, config-pin will just get in the way.

First BB-UART5-00A0.dtbo (video) and BB-SPIDEV1-00A0.dtbo (audio), need the hdmi interface disabled:

```bash
disable_uboot_overlay_video=1
```

2nd, BB-CAN0-00A0.dtbo wasn't in the repo, so i imported it:

https://github.com/beagleboard/bb.org-overlays/commit/4aad5ef0ca2bb736245489a01b8ae7eef8d466a5

Finally the big issue, BB-CAN0-00A0.dtbo needs to disable the pins used by cape universal, i just pushed that:

https://github.com/beagleboard/bb.org-overlays/commit/5741f63c1ee922333dca02d9763edae03d477c96

Now that everything is pushed to git, and the package rebuilt, just run:

```bash
sudo apt update ; sudo apt install --only-upgrade bb-cape-overlays ; sudo reboot
```

and everything should now work..

```bash
debian@beaglebone:~$ sudo /opt/scripts/tools/version.sh 
git:/opt/scripts/:[29878c8f9a13833ac69956ecc086c95b99726dde]
eeprom:[A335BNLT000C1823BBBG1273]
model:[TI_AM335x_BeagleBone_Black]
dogtag:[BeagleBoard.org Debian Image 2018-07-15]
bootloader:[microSD-(push-button)]:[/dev/mmcblk0]:[U-Boot 2018.03-00002-gac9cce7c6a]:[location: dd MBR]
kernel:[4.14.58-ti-r65]
nodejs:[v6.14.3]
uboot_overlay_options:[enable_uboot_overlays=1]
uboot_overlay_options:[uboot_overlay_addr0=/lib/firmware/BB-UART1-00A0.dtbo]
uboot_overlay_options:[uboot_overlay_addr1=/lib/firmware/BB-UART2-00A0.dtbo]
uboot_overlay_options:[uboot_overlay_addr2=/lib/firmware/BB-UART4-00A0.dtbo]
uboot_overlay_options:[uboot_overlay_addr3=/lib/firmware/BB-UART5-00A0.dtbo]
uboot_overlay_options:[uboot_overlay_addr4=/lib/firmware/BB-I2C1-00A0.dtbo]
uboot_overlay_options:[uboot_overlay_addr5=/lib/firmware/BB-SPIDEV1-00A0.dtbo]
uboot_overlay_options:[uboot_overlay_addr6=/lib/firmware/BB-CAN0-00A0.dtbo]
uboot_overlay_options:[disable_uboot_overlay_video=1]
uboot_overlay_options:[uboot_overlay_pru=/lib/firmware/AM335X-PRU-RPROC-4-14-TI-00A0.dtbo]
uboot_overlay_options:[enable_uboot_cape_universal=1]
pkg check: to individually upgrade run: [sudo apt install --only-upgrade <pkg>]
pkg:[bb-cape-overlays]:[4.4.20180731.0-0rcnee0~stretch+20180731]
pkg:[bb-wl18xx-firmware]:[1.20180517-0rcnee0~stretch+20180517]
pkg:[kmod]:[23-2rcnee1~stretch+20171005]
pkg:[librobotcontrol]:[1.0.0-git20180710.0-0rcnee0~stretch+20180712]
pkg:[firmware-ti-connectivity]:[20170823-1rcnee1~stretch+20180328]
groups:[debian : debian adm kmem dialout cdrom floppy audio dip video plugdev users systemd-journal i2c bluetooth netdev cloud9ide gpio pwm eqep admin spi tisdk weston-launch xenomai]
cmdline:[console=ttyO0,115200n8 bone_capemgr.uboot_capemgr_enabled=1 root=/dev/mmcblk0p1 ro rootfstype=ext4 rootwait coherent_pool=1M net.ifnames=0 quiet]
dmesg | grep pinctrl-single
[    1.126830] pinctrl-single 44e10800.pinmux: 142 pins at pa f9e10800 size 568
dmesg | grep gpio-of-helper
[    1.138796] gpio-of-helper ocp:cape-universal: ready
END
```

ps, you won't find can0 under /dev/, like most network interfaces, it'll be under /sys/class/net...

Regards,

**Comment by hjmagadum2002** [comment]
worked . thanks
