### ISSUE TITLE
application auto start

### ISSUE THREAD

**Issue by hjmagadum2002** [RobertCNelson/u-boot#9]
Hi,
In earlier version to to start application automatically.  /etc/rc.local present where we are starting application on boot automatically.
Now /etc/rc.local not present .  Is there any other provision there.

Regards
hemant

**Comment by RobertCNelson** [comment]
@hjmagadum2002 why did you open this up in "u-boot"..

For questions like this please use the forum:

https://groups.google.com/forum/#!forum/beagleboard

to answer you question, create a systemd service file.

Regards,
